//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekSafe
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_LostItem
    {
        public int itemID { get; set; }
        public string userIDNum { get; set; }
        public string itemName { get; set; }
        public string itemType { get; set; }
        public string itemStatus { get; set; }
        public string itemDescription { get; set; }
        public string locationFound { get; set; }
        public Nullable<System.DateTime> dateFound { get; set; }
        public string ImageURL { get; set; }
        public string username { get; set; }
    }
}
